config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope :path => "/:locale", :locale =>  /en|ru/ do

    get 'welcome/index'
    root 'welcome#index'
    root to: "home#index"

    get 'welcome/about'
    root 'welcome#about'
    root to: "home#about"

    resources :magazines
    resources :marks
    resources :products
    resources :types
    resources :items
    resources :reviews
  end
  resources :marks do
      resources :products
    end
    resources :types do
      resources :products
    end
    resources :products do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :mainPhoto, ImageUploader
	paginates_per 10
end

app/models/magazine.rb
class Magazine < ApplicationRecord
	geocoded_by :addr
	after_validation :geocode, :if => :addr_changed?
end

app/models/mark.rb
class Mark < ApplicationRecord
	has_many :products
	mount_uploader :mainPhoto, ImageUploader
	paginates_per 3

	def self.text_search(query)
		if query.present?
		   where("name @@ :q", q: query)
		else
		   all
		end
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :mark
	belongs_to :type
	has_many :orders
	has_many :reviews
	mount_uploader :mainPhoto, ImageUploader
	def self.search(search)
		if search
			where([":type_id = ?", "%#{search}%"])
		else
			all
		end
	end
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :products
	def self.text_search(query)
		if query.present?
		   where("name @@ :q", q: query)
		else
		   all
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
      @items = Item.all.page(params[:page])
    end
    def show
    	@item = Item.find(params[:id])
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  respond_to do |format|
      format.html
    end
  def index
    @marksAlf = Mark.text_search(params[:query]).page(params[:page]).order(:name)
    @marksDate = Mark.text_search(params[:query]).page(params[:page])
    gon.Alf = Mark.text_search(params[:query]).page(params[:page]).order(:name)
    gon.Date = Mark.text_search(params[:query]).page(params[:page])

    gon.m = gon.Date
        @marks = gon.m
  end

  def show
    @mark = Mark.find(params[:id])
    @products = @mark.products.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def create
    @product = Product.find(params[:product_id])
    @order = @product.orders.create(order_params)
    @order.stoim = @product.cost * @order.count
    @order.save
    @product.count -=  @order.count
    @product.save
    redirect_to marks_path
  end
  def index
    @product = Product.find(params[:product_id])
    @order = @product.orders.all
  end

  private

  def order_params
    params.require(:order).permit(:name, :count, :stoim)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<%= render 'welcome/menu' %>
<div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
<section class="content-section">

  <% @items.each do |item| %>        
    <div class="one_mark">
      <div class="box">
        <p><%= image_tag item.mainPhoto_url(:thumb).to_s, :class => ""%></p>
      </div>
      <div class="info-rest">
        <h1><%=item.name%></h1>
        <br>
        <div class="prokrutka">
          <%= item.descr %>
        </div>
      </div>
    </div>
  <% end %>
   <%= paginate @items%>

  </section>
 

</div>

app/views/marks/index.html.erb
<script type="text/javascript">
  function ch() {
    var inp = document.getElementsByName('dva');
    for (var i = 0; i < inp.length; i++) {
        if (inp[0].type == "radio" && inp[0].checked) {
            gon.m = gon.Alf;
        }
        else
          gon.m = gon.Date;
    }
}
</script>
<script type="text/javascript">
    $(document).ready(function () {
      gon.m = gon.Alf;
    });
</script>


<%= render 'welcome/menu' %>
<div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
<section class="content-section">

  <div class="d10"><h3></h3>
  <%= form_tag marks_path, class: "searchBlock", method: :get do %>
  
  <p>
    <%= text_field_tag :query, params[:query], :placeholder => "Search Events", :class => "searchLine", :size => "20" %>
    <%= submit_tag "Search", name: nil,  :class => "searchButton" %>

  </p>

<% end %>
</div>
  <% @marks.each do |mark| %>        
    <div class="one_mark">
      <div class="box">
        <p><%= image_tag mark.mainPhoto_url(:thumb).to_s, :class => ""%></p>
      </div>
      <div class="info-rest">
        <h1 style="color: black;"><%= mark.name%></h1>
        <br>
        <div class="prokrutka">
          <%= mark.descr %>
        </div>
        <a href="<%= mark_path(mark) %>"> <img style="width: 40%;" src="/img/button.png" alt="detale"></a>
      </div>
    </div>
  <% end %>
   <%= paginate @marks%>

  </section>
 

</div>

app/views/marks/show.html.erb
<%= render 'welcome/menu' %>
<div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
<section class="content-section">

<h1><%= @mark.name%></h1>


<section id="gallery">
<% @products.each do |prod| %>
 	<ul>
 		<li>
 			<article>
 				<a><%= link_to product_orders_path(prod, @order) do%>
 					<figure>
 						<%= image_tag prod.mainPhoto_url(:thumb).to_s, :class => ""%>
 						<figcaption>
 							<header>
 								<%= prod.name %>
 							</header>
 							<h2>Price: <%= prod.cost%></h2>
 							<h2>Press to detale</h2>
 						</figcaption>
 					</figure>
 					<%end%>
 				</a>
 			</article>
 		</li>
 	</ul>
 <%end%>
</section>


</section>
</div>

 

app/views/orders/index.html.erb
<%= render 'welcome/menu'%>
<div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
<section class="content-section">

<h1>Add a order:</h1>
         <%= form_with(model: [ @product, @product.orders.build ], local: true) do |form| %>
            <h1><%= @product.name%></h1>
            <p><%= image_tag @product.mainPhoto_url(:thumb).to_s, :class => ""%></p>
            <h3><%= @product.descr %><h3>
            <h1>count: <%= @product.count%>   cost:  <%= @product.cost%></h1>
         <p>
         <%= form.label :name, 'Write your name' %><br>
         <%= form.text_field :name %>
         </p>
        <p>
         <%= form.label :count, 'Write count' %><br>
         <%= form.text_field :count %>
         </p>
         <p>
            <legend>Choose shipping:</legend>
        

            <%= form.radio_button :ship, 2, :id => "2"%><label for="2" title="самовывоз">самовывоз</label><br>
     <%= form.radio_button :ship, 1, :id => "1"%><label for="1" title="доставка">доставка</label>
        </p>

        
     <p><%= form.submit %></p><br>
     <p><a href="<%= product_reviews_path(@product) %>"> <img style="width: 40%;" src="/img/button.png" alt="detale"></a></p>
      <%end%>

</section>
</div>