config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope :path => "/:locale", :locale =>  /en|ru/ do

    get 'welcome/index'
    root 'welcome#index'
    root to: "home#index"

    get 'welcome/about'
    root 'welcome#about'
    root to: "home#about"

    resources :magazines
    resources :marks
    resources :products
    resources :types
    resources :items
    resources :reviews
  end
  resources :marks do
      resources :products
    end
    resources :types do
      resources :products
    end
    resources :products do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :mainPhoto, ImageUploader
	paginates_per 10
end

app/models/magazine.rb
class Magazine < ApplicationRecord
	geocoded_by :addr
	after_validation :geocode, :if => :addr_changed?
end

app/models/mark.rb
class Mark < ApplicationRecord
	has_many :products
	mount_uploader :mainPhoto, ImageUploader
	paginates_per 3

	def self.text_search(query)
		if query.present?
		   where("name @@ :q", q: query)
		else
		   all
		end
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :mark
	belongs_to :type
	has_many :orders
	has_many :reviews
	mount_uploader :mainPhoto, ImageUploader
	def self.search(search)
		if search
			where([":type_id = ?", "%#{search}%"])
		else
			all
		end
	end
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :products
	def self.text_search(query)
		if query.present?
		   where("name @@ :q", q: query)
		else
		   all
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
      @items = Item.all.page(params[:page])
    end
    def show
    	@item = Item.find(params[:id])
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  respond_to do |format|
      format.html
    end
  def index
    @marksAlf = Mark.text_search(params[:query]).page(params[:page]).order(:name)
    @marksDate = Mark.text_search(params[:query]).page(params[:page])
    gon.Alf = Mark.text_search(params[:query]).page(params[:page]).order(:name)
    gon.Date = Mark.text_search(params[:query]).page(params[:page])

    gon.m = gon.Date
        @marks = gon.m
  end

  def show
    @mark = Mark.find(params[:id])
    @products = @mark.products.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@items = Item.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_menu.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 col-lg-3 navbar-container bg-dark">
        <!-- Вертикальное меню -->
        <nav class="navbar navbar-expand-md navbar-dark">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <!-- Пункты вертикального меню -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to (t ('menu.home')), welcome_index_url %>
              </li>
              <li class="nav-item">
                <%= link_to (t ('menu.about')), welcome_about_url %>
              </li>
              <li class="nav-item">
                <%= link_to (t ('menu.items')), items_url %>
              </li>
              <li class="nav-item">
                <%= link_to (t ('menu.marks')), marks_url %>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      
</body>
</html>

app/views/welcome/about.html.erb
  <%= render 'menu' %>

<script>
$(document).ready(function () {



var placemarks = []

   placemarks[0] = {latitude: 44.61, longitude: 33.52, hintContent: "Daria"}
 
    ymaps.ready(init);
    function init(){ 
        // Создание карты.    
        var myMap = new ymaps.Map("map", {
            center: [55.76, 37.64],
            zoom: 5
        });

 MyIconContentLayout = ymaps.templateLayoutFactory.createClass(
            '<div style="color: #FFFFFF; font-weight: bold;">$[properties.iconContent]</div>'
        ),
        placemarks.forEach(function(obj){
          var placemark = new ymaps.Placemark([obj.latitude, obj.longitude],
            {
              hintContent: obj.hintContent
            });
          myMap.geoObjects.add(placemark)
        });

    }
});</script>


<script src="https://api-maps.yandex.ru/2.1/?apikey=<85f5113c-525d-4ba2-9608-cff3a16e10ad>&lang=ru_RU" type="text/javascript"></script>

  <div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
    <div class='about_info'>
      <h1><i class="fa fa-heart-o fa-2x"></i>МЫ ЗАБОТИМСЯ О ВАШЕМ ЗДОРОВЬЕ И КРАСОТЕ</h1>
      <p>Рутинные походы в магазины косметики отменяются - чтобы купить косметику, достаточно сделать заказ онлайн. Нельзя купить красоту, но можно купить качественные средства для мейкапа и раскрыть с их помощью свою индивидуальность и творческие способности.
      <p>Последние новинки средств для макияжа, обширный каталог, в котором каждая найдет для себя ту косметику, которая подойдет именно ей, фото макияжа с использованием косметики NYX Professional Makeup, множество отзывов на продукцию - все это ты найдешь в нашем интернет-магазине. В нашем каталоге представлено множество самых разных товаров - это и косметические продукты, и аксессуары, и даже товары для беременных.</p>
      <p>Успей сделать заказ прямо сейчас!</p>
      <h1><i class="fa fa-heart-o fa-2x"></i>НАШИ СОВЕТЫ(от бъюти-блоггера леди)</h1>
      <p>Праймер сделает любой макияж более стойким и выровняет тон кожи. Он наносится на чистую кожу в качестве первого слоя. К тональному крему можно переходить только после полного высыхания базы.
      <p>В дневных образах вполне можно заменить плотный и «тяжелый» тональный крем ВВ или СС-средствами с микропигментами.</p>
      <p>Если нет времени на полноценный макияж, достаточно скорректировать брови, нанести румяна и блеск для губ натурального ягодного оттенка.
      В макияже достаточно одного акцента: можно профессионально выделить глаза в технике smoky eyes или выбрать помаду трендового темного цвета — но не все сразу.</p>
      <p>Демакияж должен стать обязательным вечерним ритуалом: только при регулярном очищении и уходе за кожей можно быть уверенной, что мэйкап будет выглядеть аккуратно.</p>
    </div>


    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>



  </div>
</div>
<div id="map" style="width: 80vw; height: 50vh; margin-left: auto; margin-right: auto;"></div>
  </div>
  
  </div>

app/views/welcome/index.html.erb
<%= render 'menu' %>


<div class="col-md-8 col-lg-9 content-container" style="background-color: #d96abb">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/img/1.jpg" alt="Первый слайд">
      <div class="carousel-caption d-none d-md-block">
        <p>Наша уходовая косметика позволит вашему лицу оставаться непревзойденным всегда!</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/img/2.jpg" alt="Второй слайд">
      <div class="carousel-caption d-none d-md-block">
        <p>Наша уходовая косметика для волос позволит вашим волосам оставаться непревзойденным всегда!</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/img/3.jpg" alt="Третий слайд">
      <div class="carousel-caption d-none d-md-block">
        <p>Наша декоративная косметика позволит вашему лицу соблазнить любого!</p>
      </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
      </div>
      <h1 style="text-align: center;">Awards</h1>
       
<section id="gallery">

        <% @items.each do |item| %> 
        

<ul>
    <li>
      <article>
          <figure>
<%= image_tag item.mainPhoto_url(:thumb).to_s, :class => ""%> 
          </figure>
         
      </article>
    </li>
  </ul>


        
          <% end %>
            </section>
            </div>